version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./octave-drift-detection
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
